/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVotarEleicaoRouteImport } from './routes/_app/votar-eleicao'
import { Route as AppRankingRouteImport } from './routes/_app/ranking'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMissionsRouteImport } from './routes/_app/missions'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppKioskRouteImport } from './routes/_app/kiosk'
import { Route as AppGroupsRouteImport } from './routes/_app/groups'
import { Route as AppFriendsRouteImport } from './routes/_app/friends'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppEleicoesOficiaisRouteImport } from './routes/_app/eleicoes-oficiais'
import { Route as AppElectionsRouteImport } from './routes/_app/elections'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDistritoRouteImport } from './routes/_app/distrito'
import { Route as AppDistrictRolesRouteImport } from './routes/_app/district-roles'
import { Route as AppClubsRouteImport } from './routes/_app/clubs'
import { Route as AppClubRolesRouteImport } from './routes/_app/club-roles'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppEleicoesOficiaisIndexRouteImport } from './routes/_app/eleicoes-oficiais.index'
import { Route as ApiPublicElectionsRouteImport } from './routes/api/public/elections'
import { Route as AppProfileIdRouteImport } from './routes/_app/profile.$id'
import { Route as AppEleicoesOficiaisIdRouteImport } from './routes/_app/eleicoes-oficiais.$id'
import { Route as AppElectionsIdRouteImport } from './routes/_app/elections.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVotarEleicaoRoute = AppVotarEleicaoRouteImport.update({
  id: '/votar-eleicao',
  path: '/votar-eleicao',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppKioskRoute = AppKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppEleicoesOficiaisRoute = AppEleicoesOficiaisRouteImport.update({
  id: '/eleicoes-oficiais',
  path: '/eleicoes-oficiais',
  getParentRoute: () => AppRoute,
} as any)
const AppElectionsRoute = AppElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDistritoRoute = AppDistritoRouteImport.update({
  id: '/distrito',
  path: '/distrito',
  getParentRoute: () => AppRoute,
} as any)
const AppDistrictRolesRoute = AppDistrictRolesRouteImport.update({
  id: '/district-roles',
  path: '/district-roles',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsRoute = AppClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AppRoute,
} as any)
const AppClubRolesRoute = AppClubRolesRouteImport.update({
  id: '/club-roles',
  path: '/club-roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppEleicoesOficiaisIndexRoute =
  AppEleicoesOficiaisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppEleicoesOficiaisRoute,
  } as any)
const ApiPublicElectionsRoute = ApiPublicElectionsRouteImport.update({
  id: '/api/public/elections',
  path: '/api/public/elections',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEleicoesOficiaisIdRoute = AppEleicoesOficiaisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEleicoesOficiaisRoute,
} as any)
const AppElectionsIdRoute = AppElectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppElectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/club-roles': typeof AppClubRolesRoute
  '/clubs': typeof AppClubsRoute
  '/district-roles': typeof AppDistrictRolesRoute
  '/distrito': typeof AppDistritoRoute
  '/documents': typeof AppDocumentsRoute
  '/elections': typeof AppElectionsRouteWithChildren
  '/eleicoes-oficiais': typeof AppEleicoesOficiaisRouteWithChildren
  '/events': typeof AppEventsRoute
  '/feed': typeof AppFeedRoute
  '/friends': typeof AppFriendsRoute
  '/groups': typeof AppGroupsRoute
  '/kiosk': typeof AppKioskRoute
  '/messages': typeof AppMessagesRoute
  '/missions': typeof AppMissionsRoute
  '/notifications': typeof AppNotificationsRoute
  '/ranking': typeof AppRankingRoute
  '/votar-eleicao': typeof AppVotarEleicaoRoute
  '/elections/$id': typeof AppElectionsIdRoute
  '/eleicoes-oficiais/$id': typeof AppEleicoesOficiaisIdRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/api/public/elections': typeof ApiPublicElectionsRoute
  '/eleicoes-oficiais/': typeof AppEleicoesOficiaisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/club-roles': typeof AppClubRolesRoute
  '/clubs': typeof AppClubsRoute
  '/district-roles': typeof AppDistrictRolesRoute
  '/distrito': typeof AppDistritoRoute
  '/documents': typeof AppDocumentsRoute
  '/elections': typeof AppElectionsRouteWithChildren
  '/events': typeof AppEventsRoute
  '/feed': typeof AppFeedRoute
  '/friends': typeof AppFriendsRoute
  '/groups': typeof AppGroupsRoute
  '/kiosk': typeof AppKioskRoute
  '/messages': typeof AppMessagesRoute
  '/missions': typeof AppMissionsRoute
  '/notifications': typeof AppNotificationsRoute
  '/ranking': typeof AppRankingRoute
  '/votar-eleicao': typeof AppVotarEleicaoRoute
  '/elections/$id': typeof AppElectionsIdRoute
  '/eleicoes-oficiais/$id': typeof AppEleicoesOficiaisIdRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/api/public/elections': typeof ApiPublicElectionsRoute
  '/eleicoes-oficiais': typeof AppEleicoesOficiaisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/club-roles': typeof AppClubRolesRoute
  '/_app/clubs': typeof AppClubsRoute
  '/_app/district-roles': typeof AppDistrictRolesRoute
  '/_app/distrito': typeof AppDistritoRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/elections': typeof AppElectionsRouteWithChildren
  '/_app/eleicoes-oficiais': typeof AppEleicoesOficiaisRouteWithChildren
  '/_app/events': typeof AppEventsRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/kiosk': typeof AppKioskRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/missions': typeof AppMissionsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/votar-eleicao': typeof AppVotarEleicaoRoute
  '/_app/elections/$id': typeof AppElectionsIdRoute
  '/_app/eleicoes-oficiais/$id': typeof AppEleicoesOficiaisIdRoute
  '/_app/profile/$id': typeof AppProfileIdRoute
  '/api/public/elections': typeof ApiPublicElectionsRoute
  '/_app/eleicoes-oficiais/': typeof AppEleicoesOficiaisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pending'
    | '/signup'
    | '/admin'
    | '/club-roles'
    | '/clubs'
    | '/district-roles'
    | '/distrito'
    | '/documents'
    | '/elections'
    | '/eleicoes-oficiais'
    | '/events'
    | '/feed'
    | '/friends'
    | '/groups'
    | '/kiosk'
    | '/messages'
    | '/missions'
    | '/notifications'
    | '/ranking'
    | '/votar-eleicao'
    | '/elections/$id'
    | '/eleicoes-oficiais/$id'
    | '/profile/$id'
    | '/api/public/elections'
    | '/eleicoes-oficiais/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pending'
    | '/signup'
    | '/admin'
    | '/club-roles'
    | '/clubs'
    | '/district-roles'
    | '/distrito'
    | '/documents'
    | '/elections'
    | '/events'
    | '/feed'
    | '/friends'
    | '/groups'
    | '/kiosk'
    | '/messages'
    | '/missions'
    | '/notifications'
    | '/ranking'
    | '/votar-eleicao'
    | '/elections/$id'
    | '/eleicoes-oficiais/$id'
    | '/profile/$id'
    | '/api/public/elections'
    | '/eleicoes-oficiais'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/pending'
    | '/signup'
    | '/_app/admin'
    | '/_app/club-roles'
    | '/_app/clubs'
    | '/_app/district-roles'
    | '/_app/distrito'
    | '/_app/documents'
    | '/_app/elections'
    | '/_app/eleicoes-oficiais'
    | '/_app/events'
    | '/_app/feed'
    | '/_app/friends'
    | '/_app/groups'
    | '/_app/kiosk'
    | '/_app/messages'
    | '/_app/missions'
    | '/_app/notifications'
    | '/_app/ranking'
    | '/_app/votar-eleicao'
    | '/_app/elections/$id'
    | '/_app/eleicoes-oficiais/$id'
    | '/_app/profile/$id'
    | '/api/public/elections'
    | '/_app/eleicoes-oficiais/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PendingRoute: typeof PendingRoute
  SignupRoute: typeof SignupRoute
  ApiPublicElectionsRoute: typeof ApiPublicElectionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/votar-eleicao': {
      id: '/_app/votar-eleicao'
      path: '/votar-eleicao'
      fullPath: '/votar-eleicao'
      preLoaderRoute: typeof AppVotarEleicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions': {
      id: '/_app/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kiosk': {
      id: '/_app/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof AppKioskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eleicoes-oficiais': {
      id: '/_app/eleicoes-oficiais'
      path: '/eleicoes-oficiais'
      fullPath: '/eleicoes-oficiais'
      preLoaderRoute: typeof AppEleicoesOficiaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/elections': {
      id: '/_app/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof AppElectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/distrito': {
      id: '/_app/distrito'
      path: '/distrito'
      fullPath: '/distrito'
      preLoaderRoute: typeof AppDistritoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/district-roles': {
      id: '/_app/district-roles'
      path: '/district-roles'
      fullPath: '/district-roles'
      preLoaderRoute: typeof AppDistrictRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clubs': {
      id: '/_app/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof AppClubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/club-roles': {
      id: '/_app/club-roles'
      path: '/club-roles'
      fullPath: '/club-roles'
      preLoaderRoute: typeof AppClubRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eleicoes-oficiais/': {
      id: '/_app/eleicoes-oficiais/'
      path: '/'
      fullPath: '/eleicoes-oficiais/'
      preLoaderRoute: typeof AppEleicoesOficiaisIndexRouteImport
      parentRoute: typeof AppEleicoesOficiaisRoute
    }
    '/api/public/elections': {
      id: '/api/public/elections'
      path: '/api/public/elections'
      fullPath: '/api/public/elections'
      preLoaderRoute: typeof ApiPublicElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile/$id': {
      id: '/_app/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eleicoes-oficiais/$id': {
      id: '/_app/eleicoes-oficiais/$id'
      path: '/$id'
      fullPath: '/eleicoes-oficiais/$id'
      preLoaderRoute: typeof AppEleicoesOficiaisIdRouteImport
      parentRoute: typeof AppEleicoesOficiaisRoute
    }
    '/_app/elections/$id': {
      id: '/_app/elections/$id'
      path: '/$id'
      fullPath: '/elections/$id'
      preLoaderRoute: typeof AppElectionsIdRouteImport
      parentRoute: typeof AppElectionsRoute
    }
  }
}

interface AppElectionsRouteChildren {
  AppElectionsIdRoute: typeof AppElectionsIdRoute
}

const AppElectionsRouteChildren: AppElectionsRouteChildren = {
  AppElectionsIdRoute: AppElectionsIdRoute,
}

const AppElectionsRouteWithChildren = AppElectionsRoute._addFileChildren(
  AppElectionsRouteChildren,
)

interface AppEleicoesOficiaisRouteChildren {
  AppEleicoesOficiaisIdRoute: typeof AppEleicoesOficiaisIdRoute
  AppEleicoesOficiaisIndexRoute: typeof AppEleicoesOficiaisIndexRoute
}

const AppEleicoesOficiaisRouteChildren: AppEleicoesOficiaisRouteChildren = {
  AppEleicoesOficiaisIdRoute: AppEleicoesOficiaisIdRoute,
  AppEleicoesOficiaisIndexRoute: AppEleicoesOficiaisIndexRoute,
}

const AppEleicoesOficiaisRouteWithChildren =
  AppEleicoesOficiaisRoute._addFileChildren(AppEleicoesOficiaisRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppClubRolesRoute: typeof AppClubRolesRoute
  AppClubsRoute: typeof AppClubsRoute
  AppDistrictRolesRoute: typeof AppDistrictRolesRoute
  AppDistritoRoute: typeof AppDistritoRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppElectionsRoute: typeof AppElectionsRouteWithChildren
  AppEleicoesOficiaisRoute: typeof AppEleicoesOficiaisRouteWithChildren
  AppEventsRoute: typeof AppEventsRoute
  AppFeedRoute: typeof AppFeedRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppKioskRoute: typeof AppKioskRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMissionsRoute: typeof AppMissionsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRankingRoute: typeof AppRankingRoute
  AppVotarEleicaoRoute: typeof AppVotarEleicaoRoute
  AppProfileIdRoute: typeof AppProfileIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppClubRolesRoute: AppClubRolesRoute,
  AppClubsRoute: AppClubsRoute,
  AppDistrictRolesRoute: AppDistrictRolesRoute,
  AppDistritoRoute: AppDistritoRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppElectionsRoute: AppElectionsRouteWithChildren,
  AppEleicoesOficiaisRoute: AppEleicoesOficiaisRouteWithChildren,
  AppEventsRoute: AppEventsRoute,
  AppFeedRoute: AppFeedRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppKioskRoute: AppKioskRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMissionsRoute: AppMissionsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRankingRoute: AppRankingRoute,
  AppVotarEleicaoRoute: AppVotarEleicaoRoute,
  AppProfileIdRoute: AppProfileIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PendingRoute: PendingRoute,
  SignupRoute: SignupRoute,
  ApiPublicElectionsRoute: ApiPublicElectionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
